name: Deploy to Azure

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r replica/m365/apps/requirements.txt

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Create deployment package
      run: |
        cd replica/m365/apps
        zip -r ../../../app.zip . -x "*.git*" "*.DS_Store*"

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: boopas-graph-connector-api
        package: app.zip

    - name: Set App Service startup command
      run: |
        az webapp config set --resource-group boopas-copilot-centralus-rg --name boopas-graph-connector-api --startup-file "gunicorn graph_connector_api:app"

    - name: Set environment variables
      run: |
        az webapp config appsettings set --resource-group boopas-copilot-centralus-rg --name boopas-graph-connector-api --settings AZURE_TENANT_ID="${{ secrets.AZURE_TENANT_ID }}" AZURE_CLIENT_ID="${{ secrets.AZURE_CLIENT_ID }}"

    - name: Restart App Service
      run: |
        az webapp restart --resource-group boopas-copilot-centralus-rg --name boopas-graph-connector-api
